/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trafficdatabasesystem;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static trafficdatabasesystem.DrivingIDForm.getDiffYears;
import static trafficdatabasesystem.Global.date;

/**
 *
 * @author Ahmed El-Hussein
 */
public class CarLicenceForm extends javax.swing.JFrame {
 
        int FoundFlag=0;
        int noCarLicenceFlag=1;
        int dif;
        CarLicence newCarLicence=new CarLicence();
    /**
     * Creates new form CarLicenceForm
     */
    public CarLicenceForm() {
        initComponents();
     setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                  int answer = JOptionPane.showConfirmDialog(null, 
		"Are you sure you want to close?",null, 
        JOptionPane.YES_NO_OPTION);

    if (answer == JOptionPane.NO_OPTION) {
        new CarLicenceForm().setVisible(true);
    }
    
    else if(answer == JOptionPane.YES_OPTION) {
    try{
        FileWriter writer = new FileWriter("CarLicence.txt"); 
        for(CarLicence str: Global.CarLicenceList) {
            String name=str.getName();
            String address=str.getAddress();
            String DateOfIssue=Global.formatter.format(str.getDateOfIssue());
            String DateOfexp=Global.formatter.format(str.getDateOfExpiry());
            String CarPlate=str.getcPlate().getCarPlateNumber();
            String Nationality=str.getNationality();
            String carInspection= String.valueOf(str.isCarInspection());
            String CarChassisNumber=String.valueOf(str.getCarChassisNumber());
            String CarManuf=str.getCarManufacturer();
            String CarModel=str.getCarModel();
            String DateOfManufacturing=String.valueOf(str.getDateOfManufacturing());
            String engineCapcity=String.valueOf(str.getEngineCapacity());
            String CarColour=str.getCarColor();
            String Violations=String.valueOf(str.getViolations());
            writer.write(name + System.lineSeparator() + address + System.lineSeparator()+DateOfIssue + System.lineSeparator()+DateOfexp + System.lineSeparator()+CarPlate + System.lineSeparator()+ Nationality + System.lineSeparator()+carInspection + System.lineSeparator()+CarChassisNumber + System.lineSeparator()+CarManuf + System.lineSeparator()+CarModel + System.lineSeparator()+DateOfManufacturing + System.lineSeparator()+engineCapcity + System.lineSeparator()+CarColour + System.lineSeparator()+Violations+ System.lineSeparator());
            }
            writer.close();
        }                    
    catch (IOException ex) {
            Logger.getLogger(CarLicenceForm.class.getName()).log(Level.SEVERE, null, ex);
       }

    try{
        FileWriter writer2 = new FileWriter("CarPlateNumbers.txt"); 
        for(CarPlate str: Global.carPlateNumbers) {
          String platenumber=str.getCarPlateNumber();
          writer2.write(platenumber + System.lineSeparator());
       }
        writer2.close();
    }                    
    catch (IOException ex) {
        Logger.getLogger(CarLicenceForm.class.getName()).log(Level.SEVERE, null, ex);
    }
 }

         e.getWindow().dispose();
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IssueNewCarLicenceButton = new javax.swing.JButton();
        ViewOrPayCarLicenceViolations = new javax.swing.JButton();
        RenewCarLicenceButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Licence");
        setMinimumSize(new java.awt.Dimension(713, 481));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Car Licence");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(230, 10, 360, 90);

        IssueNewCarLicenceButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        IssueNewCarLicenceButton.setText("Issue New CarLicence");
        IssueNewCarLicenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueNewCarLicenceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(IssueNewCarLicenceButton);
        IssueNewCarLicenceButton.setBounds(320, 110, 360, 93);

        ViewOrPayCarLicenceViolations.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ViewOrPayCarLicenceViolations.setText("View/Pay CarLicence Violations");
        ViewOrPayCarLicenceViolations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrPayCarLicenceViolationsActionPerformed(evt);
            }
        });
        jPanel2.add(ViewOrPayCarLicenceViolations);
        ViewOrPayCarLicenceViolations.setBounds(320, 330, 359, 90);

        RenewCarLicenceButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RenewCarLicenceButton.setText("Renew CarLicence");
        RenewCarLicenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenewCarLicenceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(RenewCarLicenceButton);
        RenewCarLicenceButton.setBounds(320, 220, 360, 93);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trafficdatabasesystem/ID Form.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 720, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IssueNewCarLicenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueNewCarLicenceButtonActionPerformed
        // TODO add your handling code here:
             
          Global.GlobalID = Long.parseLong(JOptionPane.showInputDialog("Enter your National ID:"));
            for(NationalID k:Global.nationalIDList)
            {
                if(k.getNationalID()==Global.GlobalID)
                {
                       noCarLicenceFlag=1;
                       FoundFlag=1;
                       
                      dif=getDiffYears( k.getDateOfBirth(), date);
                      if(dif>=21){
                      Global.CarChassisNumber = Integer.parseInt(JOptionPane.showInputDialog("Enter the car chassis number"));
                       for(CarLicence cL:Global.CarLicenceList)
                        {       
                           if(cL.getCarChassisNumber() == Global.CarChassisNumber){
                               JOptionPane.showMessageDialog(null, "There is a licence of a car with this chassis number");noCarLicenceFlag=0;break;}
                         
                        }

                        if(noCarLicenceFlag==1)
                            {  

                                 Global.GlobalNationalID=k;
                                this.setVisible(false);//Closing the Current frame
                                new IssueNewCarLicence().setVisible(true);// Opening a new frame
                                  break;
                            }
                      else if(noCarLicenceFlag==0){break;}
                      }
                      else
                          JOptionPane.showMessageDialog(null, "You haven't met the legal age to issue this document!");
                        
                }}

         if(FoundFlag!=1)
           { JOptionPane.showMessageDialog(null, "CHECK THE NATIONAL ID AGAIN PLEASE!");}


    }//GEN-LAST:event_IssueNewCarLicenceButtonActionPerformed

    private void RenewCarLicenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenewCarLicenceButtonActionPerformed
        // TODO add your handling code here:
         Global.CarChassisNumber = Integer.parseInt(JOptionPane.showInputDialog("Enter your car's chassis number:"));
         Object[] renewalOptions = {1,3};
         Global.carLicenceNumberOfYears =(Integer)JOptionPane.showInputDialog(null, "Enter your renewal period:", "Enter your renewal period:", JOptionPane.PLAIN_MESSAGE, null, renewalOptions, "1");
         
    Global.cal.setTime(Global.date);
    Global.cal.add(Calendar.YEAR, Global.carLicenceNumberOfYears);       //To be implemented in method.

         for(CarLicence c:Global.CarLicenceList)
                        {       
                           if(c.getCarChassisNumber()==Global.CarChassisNumber)
                           {
                               if(c.getViolations()==0){
                             c.setDateOfIssue(Global.date);
                             c.setDateOfExpiry(Global.cal.getTime());
                             System.out.print(c.getDateOfIssue()+"\n"+c.getDateOfExpiry());
                             JOptionPane.showMessageDialog(null, "Your Car Licence has been renewed and is set to expire on " + c.getDateOfExpiry());
                               }
                               else
                             JOptionPane.showMessageDialog(null, "You Must pay your VIOLATIONS first ");
                            }
                        }
    }//GEN-LAST:event_RenewCarLicenceButtonActionPerformed

    private void ViewOrPayCarLicenceViolationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrPayCarLicenceViolationsActionPerformed
        // TODO add your handling code here:
        String plate = JOptionPane.showInputDialog("Enter your plate number :");
  for(CarLicence k:Global.CarLicenceList)
      {
  if(k.getcPlate().getCarPlateNumber().equals(plate)){
      int answer = JOptionPane.showConfirmDialog(null,"Your VIOLATIONS COST is: "+k.getViolations()+ 
		"\n Do you want to pay the bill?",null, 
        JOptionPane.YES_NO_OPTION);

if (answer == JOptionPane.NO_OPTION) {    
JOptionPane.showMessageDialog(null, "YOUR VIOLATIONS COST: "+k.getViolations()); break;  

 }
 else if(answer == JOptionPane.YES_OPTION) {
        long visa =Long.parseLong(JOptionPane.showInputDialog("Enter your VISA number :"));
        k.setViolations(0);
        JOptionPane.showMessageDialog(null,"Payment done successfully");
        break;
             }


          }
       }
    }//GEN-LAST:event_ViewOrPayCarLicenceViolationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarLicenceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarLicenceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarLicenceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarLicenceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarLicenceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IssueNewCarLicenceButton;
    private javax.swing.JButton RenewCarLicenceButton;
    private javax.swing.JButton ViewOrPayCarLicenceViolations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
