package trafficdatabasesystem;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.Calendar;
import static java.util.Calendar.YEAR;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static trafficdatabasesystem.Global.date;

/**
 *
 * @author Tasnem
 */
public class DrivingIDForm extends javax.swing.JFrame {

        int FoundFlag=0;
        int noDrvIDFlag=1;
        int dif;
        DrivingID newDRVID=new DrivingID();
    /**
     * Creates new form DrivingIDForm
     */
    public DrivingIDForm() {
        initComponents();
     setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                  int answer = JOptionPane.showConfirmDialog(null, 
		"Are you sure you want to close?",null, 
        JOptionPane.YES_NO_OPTION);

if (answer == JOptionPane.NO_OPTION) {  

 new DrivingIDForm().setVisible(true);
 }
 else if(answer == JOptionPane.YES_OPTION) {
try{
  	FileWriter writer = new FileWriter("DrivingID.txt"); 
for(DrivingID str: Global.DrivingIDList) {
String name=str.getName();
String address=str.getAddress();
String nationalID=String.valueOf(str.getNationalID());
String Job=str.getJob();
String DateOfIssue=Global.formatter.format(Global.GlobalNationalID.getDateOfIssue());
String DateOfexp=Global.formatter.format(Global.GlobalNationalID.getDateOfExpiry());
String Nationality=str.getNationality();
String testPassed=String.valueOf(str.isTestPassed());
String OptGlasses=String.valueOf(str.isOpticalGlasses());
String Violations=String.valueOf(str.getViolations());
  writer.write(name + System.lineSeparator() + address + System.lineSeparator()+nationalID + System.lineSeparator()+Job + System.lineSeparator()+DateOfIssue + System.lineSeparator()+ DateOfexp + System.lineSeparator()+Nationality + System.lineSeparator()+testPassed + System.lineSeparator()+OptGlasses + System.lineSeparator()+Violations+ System.lineSeparator());
}
writer.close();
}                    
 catch (IOException ex) {
                          Logger.getLogger(DrivingIDForm.class.getName()).log(Level.SEVERE, null, ex);
                      }
}

               e.getWindow().dispose();
            }
            
            
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
public static Calendar getCalendar(Date date) {
    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    return cal;
}
    public static int getDiffYears(Date first, Date last) {
    Calendar a = getCalendar(first);
    Calendar b = getCalendar(last);
    int diff = b.get(YEAR) - a.get(YEAR);
return diff;}


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RenewDrivingIDButton = new javax.swing.JButton();
        IssueNewDrivingIDButton = new javax.swing.JButton();
        ViewOrPayDrivingIDViolations = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Driving ID");
        setMinimumSize(new java.awt.Dimension(713, 481));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Driving ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(230, 10, 360, 90);

        RenewDrivingIDButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RenewDrivingIDButton.setText("Renew Driving ID");
        RenewDrivingIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenewDrivingIDButtonActionPerformed(evt);
            }
        });
        jPanel2.add(RenewDrivingIDButton);
        RenewDrivingIDButton.setBounds(309, 230, 380, 93);

        IssueNewDrivingIDButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        IssueNewDrivingIDButton.setText("Issue New Driving ID");
        IssueNewDrivingIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueNewDrivingIDButtonActionPerformed(evt);
            }
        });
        jPanel2.add(IssueNewDrivingIDButton);
        IssueNewDrivingIDButton.setBounds(310, 120, 380, 93);

        ViewOrPayDrivingIDViolations.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ViewOrPayDrivingIDViolations.setText("View/Pay Driving ID Violations");
        ViewOrPayDrivingIDViolations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrPayDrivingIDViolationsActionPerformed(evt);
            }
        });
        jPanel2.add(ViewOrPayDrivingIDViolations);
        ViewOrPayDrivingIDViolations.setBounds(310, 340, 378, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trafficdatabasesystem/ID Form.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
        
    private void RenewDrivingIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenewDrivingIDButtonActionPerformed
        // TODO add your handling code here:
        // readFiles();
 Global.GlobalID = Long.parseLong(JOptionPane.showInputDialog("Enter your National ID:"));

    Global.cal.setTime(Global.date);
    Global.cal.add(Calendar.YEAR, 7);       

         for(DrivingID d:Global.DrivingIDList)
                        {       
                           if(d.getNationalID()==Global.GlobalID)
                           {
                               if(d.getViolations()==0){
                             d.setDateOfIssue(Global.date);
                             d.setDateOfExpiry(Global.cal.getTime());
                             System.out.print(d.getDateOfIssue()+"\n"+d.getDateOfExpiry());
                             JOptionPane.showMessageDialog(null, "Your Driving ID has been renewed and is set to expire on " + d.getDateOfExpiry());
                               }
                               else
                             JOptionPane.showMessageDialog(null, "You Must pay your VIOLATIONS first ");

                            }
                        }
    }//GEN-LAST:event_RenewDrivingIDButtonActionPerformed

    private void IssueNewDrivingIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueNewDrivingIDButtonActionPerformed
        // TODO add your handling code here:
              
          Global.GlobalID = Long.parseLong(JOptionPane.showInputDialog("Enter your National ID:"));
            for(NationalID k:Global.nationalIDList)
            {
                if(k.getNationalID()==Global.GlobalID)
                {
                       noDrvIDFlag=1;
                       FoundFlag=1;
                       
                      dif=getDiffYears( k.getDateOfBirth(), date);
                     if(dif>=18){
                      for(DrivingID d:Global.DrivingIDList)
                        {       
                           if(d.getNationalID()==Global.GlobalID){
                               JOptionPane.showMessageDialog(null, "There is a Driving ID assigned with this citizen");noDrvIDFlag=0;break;}
                         
                        }
                        if(noDrvIDFlag==1)
                            {  

                                 Global.GlobalNationalID=k;
                                this.setVisible(false);//Closing the Current frame
                                new IssueNewDrivingIDForm().setVisible(true);// Opening a new frame
                                  break;
                            }else if(noDrvIDFlag==0){break;}}
                                   else
                          JOptionPane.showMessageDialog(null, "You haven't met the legal age to issue this document!");
                }
                       
            }
         if(FoundFlag!=1)
           { JOptionPane.showMessageDialog(null, "CHECK THE NATIONAL ID AGAIN PLEASE!");}

    }//GEN-LAST:event_IssueNewDrivingIDButtonActionPerformed

    private void ViewOrPayDrivingIDViolationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrPayDrivingIDViolationsActionPerformed
        // TODO add your handling code here:
        
Global.GlobalID = Long.parseLong(JOptionPane.showInputDialog("Enter your National ID:"));
  for(DrivingID k:Global.DrivingIDList)
            {
  if(k.getNationalID()==Global.GlobalID){
      int answer = JOptionPane.showConfirmDialog(null,"Your VIOLATIONS COST is: "+k.getViolations()+ 
		"\n Do you want to pay the bill?",null, 
        JOptionPane.YES_NO_OPTION);

if (answer == JOptionPane.NO_OPTION) {      
JOptionPane.showMessageDialog(null, "YOUR VIOLATIONS COST: "+k.getViolations()); break;

 }
 else if(answer == JOptionPane.YES_OPTION) {
        long visa =Long.parseLong( JOptionPane.showInputDialog("Enter your VISA number :"));
        k.setViolations(0);
        JOptionPane.showMessageDialog(null,"Payment done successfully");
        break;
 
 }


}
}

    }//GEN-LAST:event_ViewOrPayDrivingIDViolationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrivingIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrivingIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrivingIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrivingIDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrivingIDForm().setVisible(true);
       
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IssueNewDrivingIDButton;
    private javax.swing.JButton RenewDrivingIDButton;
    private javax.swing.JButton ViewOrPayDrivingIDViolations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
