/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trafficdatabasesystem;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed El-Hussein
 */
public class IssueNewCarLicence extends javax.swing.JFrame {

    /**
     * Creates new form IssueNewCarLicence
     */
    public IssueNewCarLicence() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        CarPlateField = new javax.swing.JTextField();
        CarChassisNoField = new javax.swing.JTextField();
        DateOfIssueField = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        NationalityField = new javax.swing.JTextField();
        DateOfExpField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ConfirmationButton = new javax.swing.JButton();
        LoadDataButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DateOfManuField = new javax.swing.JTextField();
        EngineCapacityField = new javax.swing.JTextField();
        CarColourField = new javax.swing.JTextField();
        CarManufacturerField = new javax.swing.JTextField();
        CarModelField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1108, 528));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Issue New Car Licence");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 650, 90);

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(NameField);
        NameField.setBounds(190, 150, 300, 30);
        jPanel2.add(AddressField);
        AddressField.setBounds(190, 200, 300, 30);

        CarPlateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarPlateFieldActionPerformed(evt);
            }
        });
        jPanel2.add(CarPlateField);
        CarPlateField.setBounds(200, 240, 150, 30);

        CarChassisNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarChassisNoFieldActionPerformed(evt);
            }
        });
        jPanel2.add(CarChassisNoField);
        CarChassisNoField.setBounds(310, 280, 150, 30);

        DateOfIssueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateOfIssueFieldActionPerformed(evt);
            }
        });
        jPanel2.add(DateOfIssueField);
        DateOfIssueField.setBounds(700, 160, 190, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("Car Inspection");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(710, 420, 126, 40);
        jPanel2.add(NationalityField);
        NationalityField.setBounds(700, 240, 260, 30);
        jPanel2.add(DateOfExpField);
        DateOfExpField.setBounds(700, 200, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 150, 60, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DOI:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(530, 160, 44, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DOE:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(530, 200, 46, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Nationality:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(530, 240, 105, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Address:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(90, 200, 78, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Car Plate:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 240, 90, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Car Chassis Number:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 280, 200, 22);

        ConfirmationButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ConfirmationButton.setText("Confirm");
        ConfirmationButton.setEnabled(false);
        ConfirmationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmationButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ConfirmationButton);
        ConfirmationButton.setBounds(860, 420, 151, 51);

        LoadDataButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoadDataButton.setText("Load Data");
        LoadDataButton.setActionCommand("Load");
        LoadDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadDataButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoadDataButton);
        LoadDataButton.setBounds(150, 440, 120, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Car Manufacturer:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(90, 320, 170, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Car Model:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(90, 360, 120, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Date Of Manufacturing:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(530, 280, 250, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Engine Capacity:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(530, 320, 180, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Car Colour:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(530, 360, 130, 20);
        jPanel2.add(DateOfManuField);
        DateOfManuField.setBounds(760, 280, 210, 30);
        jPanel2.add(EngineCapacityField);
        EngineCapacityField.setBounds(730, 320, 250, 30);
        jPanel2.add(CarColourField);
        CarColourField.setBounds(660, 360, 240, 30);
        jPanel2.add(CarManufacturerField);
        CarManufacturerField.setBounds(270, 320, 220, 30);
        jPanel2.add(CarModelField);
        CarModelField.setBounds(250, 360, 230, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(640, 440, 50, 20);

        jLabel15.setText("YEARS");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(590, 440, 50, 14);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trafficdatabasesystem/IssueDocument.png"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 0, 1120, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarPlateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarPlateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarPlateFieldActionPerformed

    private void CarChassisNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarChassisNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarChassisNoFieldActionPerformed

    private void DateOfIssueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateOfIssueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateOfIssueFieldActionPerformed

    private void ConfirmationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmationButtonActionPerformed
        // TODO add your handling code here:
        CarLicence cl=new CarLicence(); //gow ashan lw bara hykrar
        CarPlate cP=new CarPlate();
        //fileList.add(sc.nextLine());
        cl.setName(NameField.getText());
        cl.setAddress(AddressField.getText());
        cl.setDateOfIssue(Global.date); //DATE FORMAT IS TO BE DEBUGGED
        cl.setDateOfExpiry(Global.cal.getTime());
        cl.setNationality(NationalityField.getText());
        cP.setCarPlateNumber(CarPlateField.getText());
        cl.setcPlate(cP);
        cl.setCarChassisNumber(Global.CarChassisNumber);
        cl.setNationality(NationalityField.getText());
        cl.setCarManufacturer(CarManufacturerField.getText());
        cl.setDateOfManufacturing(Integer.parseInt(DateOfManuField.getText()));
        cl.setCarModel(CarModelField.getText());
        cl.setEngineCapacity(Integer.parseInt(EngineCapacityField.getText()));
        cl.setCarColor(CarColourField.getText());

        if(jCheckBox1.isSelected()) {
            //not checked
            cl.setCarInspection(true);
        } else {
            cl.setCarInspection(false);
        }

        Global.CarLicenceList.add(cl);
        JOptionPane.showMessageDialog(null, "Done Successfully!\nYou can take your Car Licence after 2 days!");
        this.setVisible(false);//Closing the Current frame
        new CarLicenceForm().setVisible(true);// Opening a new frame
    }//GEN-LAST:event_ConfirmationButtonActionPerformed

    private void LoadDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadDataButtonActionPerformed
        // TODO add your handling code here:
        NameField.setText ( Global.GlobalNationalID.getName());
        AddressField.setText(Global.GlobalNationalID.getAddress());
        CarPlateField.setText(CarPlate.generateNumbers());    //Plate Number generated from method
        CarChassisNoField.setText(String.valueOf(Global.CarChassisNumber));// !!!!
        NationalityField.setText("Egyptian");
        Global.cal.setTime(Global.date);
        Global.cal.add(Calendar.YEAR,Integer.parseInt((String) jComboBox1.getSelectedItem()));
        DateOfIssueField.setText(Global.formatter.format(Global.date));
        DateOfExpField.setText(Global.formatter.format(Global.cal.getTime()));
        LoadDataButton.setVisible(false);
    }//GEN-LAST:event_LoadDataButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected() && !LoadDataButton.isVisible())
            ConfirmationButton.setEnabled(true);
        else
            ConfirmationButton.setEnabled(false);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueNewCarLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueNewCarLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueNewCarLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueNewCarLicence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueNewCarLicence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JTextField CarChassisNoField;
    private javax.swing.JTextField CarColourField;
    private javax.swing.JTextField CarManufacturerField;
    private javax.swing.JTextField CarModelField;
    private javax.swing.JTextField CarPlateField;
    private javax.swing.JButton ConfirmationButton;
    private javax.swing.JTextField DateOfExpField;
    private javax.swing.JTextField DateOfIssueField;
    private javax.swing.JTextField DateOfManuField;
    private javax.swing.JTextField EngineCapacityField;
    private javax.swing.JButton LoadDataButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField NationalityField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
