package trafficdatabasesystem;

import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Tasnem
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setMinimumSize(new java.awt.Dimension(767, 514));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(124, 196, 193));
        jPanel2.setLayout(null);
        jPanel2.add(Password);
        Password.setBounds(270, 260, 287, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Traffic Database System");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 10, 660, 60);
        jPanel2.add(ID);
        ID.setBounds(270, 190, 290, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Employee ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(120, 210, 101, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 280, 74, 22);

        LoginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LoginButton.setText("LOGIN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButton);
        LoginButton.setBounds(270, 320, 290, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trafficdatabasesystem/Login.png"))); // NOI18N
        jLabel4.setText("T");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(-40, 60, 770, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        try
        {
            //Reading Employees File
            Scanner sc = new Scanner(new File("Employee.txt"));
            while (sc.hasNextLine())
            {
                Global.fileList.add(sc.nextLine());
            }
            sc.close();

            if(Global.fileList.size() % 2 == 0)
            {
                int flagPass = 0,flagEmpID = 0;
                for(int i=0;i<Global.fileList.size();i+=2)
                {
                    int k = i + 1;
                    if(Global.fileList.get(i).equals(ID.getText()))
                    {
                        flagEmpID = 1;
                        if(Global.fileList.get(k).equals(new String(Password.getPassword())))
                        {
                            CarLicenceEmployee CLE = new CarLicenceEmployee();
                            DrivingIDEmployee DIDE = new DrivingIDEmployee();
                            if(CLE.checkPassword(new String(Password.getPassword())))
                            //Access Car Licence Employee Form
                            {
                                JOptionPane.showMessageDialog(null, "Car Licence Employee ACCESSED!");
                                flagPass = 1;
                                this.setVisible(false);//Closing the Current frame
                                new CarLicenceForm().setVisible(true);// Opening a new frame
                            }

                            else if(DIDE.checkPassword(new String(Password.getPassword())))
                            //Access Driving ID Employee Form
                            {
                                JOptionPane.showMessageDialog(null, "Driving ID Employee ACCESSED!");   
                                flagPass = 1;
                                this.setVisible(false);//Closing the Current frame
                                new DrivingIDForm().setVisible(true);// Opening a new frame
                            }
                        }
                    }
                }
                if (flagEmpID == 0)
                JOptionPane.showMessageDialog(null, "Employee Not Found!");
                else if (flagPass == 0)
                JOptionPane.showMessageDialog(null, "Incorrect Password!");
            }
            else
            JOptionPane.showMessageDialog(null, "Data read from Employees file is not complete! Please Recheck the Employees Database.");
        
SimpleDateFormat DayMonthYear =  new SimpleDateFormat("dd/MM/yyyy");
           
    //Reading NationalID File
     sc = new Scanner(new File("NationalID.txt"));
         while (sc.hasNextLine())
        {
  NationalID n = new NationalID();
            n.setName(sc.nextLine());
            n.setAddress(sc.nextLine());
            n.setNationalID(Long.parseLong(sc.nextLine()));
            n.setJob(sc.nextLine());
            n.setDateOfBirth((Date)DayMonthYear.parse(sc.nextLine()));
            n.setDateOfIssue((Date)DayMonthYear.parse(sc.nextLine()));
            n.setDateOfExpiry((Date)DayMonthYear.parse(sc.nextLine()));
            Global.nationalIDList.add(n);
        }
        sc.close();
        
        //Reading DrivingID File
        sc = new Scanner(new File("DrivingID.txt"));
        while (sc.hasNextLine())
        {
            DrivingID d=new DrivingID(); 
            d.setName(sc.nextLine());
            d.setAddress(sc.nextLine());
            d.setNationalID(Long.parseLong(sc.nextLine()));
            d.setJob(sc.nextLine());
            d.setDateOfIssue((Date)DayMonthYear.parse(sc.nextLine()));
            d.setDateOfExpiry((Date)DayMonthYear.parse(sc.nextLine()));
            d.setNationality((sc.nextLine()));
            d.setTestPassed(Boolean.parseBoolean(sc.nextLine()));
            d.setOpticalGlasses(Boolean.parseBoolean(sc.nextLine()));
            d.setViolations(Double.parseDouble(sc.nextLine()));
            Global.DrivingIDList.add(d);
        }
   sc.close();


    //Reading CarLicences File
            sc = new Scanner(new File("CarLicence.txt"));
            while(sc.hasNextLine())
            {
                CarLicence cL = new CarLicence();
                CarPlate cP = new CarPlate();
                cL.setName(sc.nextLine());
                cL.setAddress(sc.nextLine());
                cL.setDateOfIssue((Date)DayMonthYear.parse(sc.nextLine()));
                cL.setDateOfExpiry((Date)DayMonthYear.parse(sc.nextLine()));
                cP.setCarPlateNumber(sc.nextLine());
                cL.setcPlate(cP);
                cL.setNationality(sc.nextLine());
                cL.setCarInspection((Boolean.parseBoolean(sc.nextLine())));
                cL.setCarChassisNumber(Integer.parseInt(sc.nextLine()));
                cL.setCarManufacturer(sc.nextLine());
                cL.setCarModel(sc.nextLine());
                cL.setDateOfManufacturing(Integer.parseInt(sc.nextLine()));
                cL.setEngineCapacity(Integer.parseInt(sc.nextLine()));
                cL.setCarColor(sc.nextLine());
                cL.setViolations(Double.parseDouble(sc.nextLine()));
                
                Global.CarLicenceList.add(cL);
                Global.carPlateNumbers.add(cP);
            }
               sc.close();

}
        
        catch (FileNotFoundException | ParseException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
